### ISSUE TITLE
Log.CloseAndFlush doesn't send buffered events

### ISSUE THREAD

**Issue by JosephDSchwartz** [billpratt/serilog-sinks-sumologic#10]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 2.2.0

### Description
Calling `Log.CloseAndFlush` doesn't seem to send buffered events like it should. In fact, it causes an exception to be thrown if there are any. Here's an example of the exception:

![loggingerror](https://user-images.githubusercontent.com/6923910/28979012-6889b140-7905-11e7-816a-c10268296d21.PNG)

The problem seems to stem from `SumoLogicSink.Dispose` disposing the `_httpClient` is uses, but not calling `base.Dispose(disposing)` before hand. So the next time the timer on the base class ticks and `_httpClient` is used, the exception above is thrown.

### Steps to recreate
With a console application:
1. Enable `Serilog.Debugging.SelfLog` to log to the console.
2. Queue up a few events.
3. Call `Log.CloseAndFetch` while there are still buffered events in the queue.
4. Use a `Console.Read`, or something equivalent, to wait until the timer ticks and the exception is thrown.

### Current behavior
`Log.CloseAndFlush` doesn't send buffered events.

### Expected behavior
`Log.CloseAndFlush` should send buffered events.

**Comment by billpratt** [comment]
Thanks for reporting this. I'll be sure to take a look as soon as possible.

**Comment by billpratt** [comment]
@JosephDSchwartz I believe this is fixed with 6cebb067957dc75bb3dfcabd7036adeffbc1f7dd. I'll push out a new version shortly

**Comment by JosephDSchwartz** [comment]
@billpratt that fixed the problem I was having perfectly! Feel free to close this issue when you get that new version out, and thanks a ton on the quick turn around time! Really appreciate it :smiley:

**Comment by billpratt** [comment]
Published v2.3 to nuget with the fix. Thanks for the bug report! https://www.nuget.org/packages/Serilog.Sinks.SumoLogic/2.3.0
