### ISSUE TITLE
Usable with serilog-settings-configuration?

### ISSUE THREAD

**Issue by seangwright** [billpratt/serilog-sinks-sumologic#2]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.0.2

### Description
Is this package usable with the settings configuration approach?

```
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(Configuration)
    .CreateLogger();
```

### Steps to recreate
My `appsettings.json` looks like this now

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Literate" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      { "Name": "LiterateConsole" },
      {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "serilogs//Proj.Api-{Date}.txt"
        }
      },
      {
        "Name": "SumoLogic",
        "endpointUrl": "https://endpoint2.collection.us2.sumologic.com/receiver/v1/http/collection-guid"
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Properties": {
      "Application": "Proj"
    }
  },
}
```

### Current behavior
Unknown

### Expected behavior
Configure Sumo Logic sink from `appsettings.json`

**Comment by billpratt** [comment]
I don't believe it works currently. It's something to look into. I want to add in support for ASP.NET Core configuration but havent had the time. I'd be happy to review a PR if you are interested in this setup.

**Comment by tdawgy** [comment]
I believe this issue can be closed, the below example is working as expected for me :)

`"Serilog": {
        "MinimumLevel": {
            "Default": "Information",
            "Override": {
                "System": "Warning",
                "Microsoft": "Warning"
            }
        },
        "WriteTo": [
            `{`
                "Name": "SumoLogic",
                "Args": {
                    "endpointUrl": (endpointUrl goes here)
                }
            }
        ]
    }`
