### ISSUE TITLE
Allow outputTemplate string parameter

### ISSUE THREAD

**Issue by slowvincy** [billpratt/serilog-sinks-sumologic#9]
We have a need to display {SourceContext} in every log message to indicate the originated class and currently been overriding ITextFormatter. However this does not work with the AppSettings.json approach in ASP.NET Core. Could you provide functionality to just enable string of outputTemplate parameter, much like what LiterateConsole does? Thanks!

**Comment by billpratt** [comment]
Can you provide an example of how you would like to use this with the appsettings.json approach?

**Comment by slowvincy** [comment]
Hi @billpratt please see https://github.com/serilog/serilog-settings-configuration. Thanks.

**Comment by billpratt** [comment]
I haven't used the appsettings approach yet. I will look into this when I have a chance but I'm happy to review a PR if you want to submit one.

**Comment by billpratt** [comment]
@slowvincy Please see 20dfdfc53c72dfe200d3fb3ff0154920c11f6e8a. This change has been deployed to nuget in version 2.2

**Comment by slowvincy** [comment]
Thank you!
